---
title: "Regression analysis of Wine Quality based on its physicochemical properties"
subtitle: "based on white Vinho Verde wine from Portugal"
author: "Ziyao Han"
thanks: "Code and data are available at: https://github.com/HanFrank/Analysis-of-Wine-Quality-based-on-its-physicochemical-properties"
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: "Wine is one of the most widely consumed beverages in the world with significant cultural influence. In this paper the physicochemical properties of wine will be compared with the precieved quality of wine by wine experts. Even though the preference for wine taste is highly subjective, this study may help identify objective components for wine preference. *Sentence should be about results and findings which have not been completed at time of writing*."
output:
  bookdown::pdf_document2
toc: FALSE
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(knitr)
library(bookdown)
library(kableExtra)
library(ggplot2)
```

# Introduction

Wine is one of the most widely consumed beverages in the world with significant cultural influence. Wine is made through an arduous process of selecting fruit, processing, fermentation, and ageing with many small intricacies that impact the final product. The sugar and acid levels of the fruit and ageing vessels are just some of the ways that the taste of the final product can be changed [@citeWine]. Wine has historically been consumed as a part of cultural and religious ceremonies throughout the world and is a part of the cultural identities of many countries, especially in Europe [@citeHistory].

In this report, the dataset that will be used was obtained from UCI's (University of California Irvine) Machine Learning Repository and will be used for statistical modelling and visualization of the data. Some of the physicochemical variables include: Citric acid, residual sugar, chlorides, pH, and alcohol percentage. The wine's quality was graded by various wine experts on a scale of 0 (very bad) to 10 (very excellent) [@citeVinho]. Moreover, this report will use Multiple Linear Regression along with Model selection techniques in order to create an appropriate model for modelling wine quality. Furthermore, this report will interpret the results of the determined model and discuss the possible implications.

The preference for the taste of wine is highly subjective just like with all other foods and drinks. There have been many studying showing that even many experts in blind taste tests cannot accurately differentiate between cheap and expensive wines [@citeTasting]. Thus, the possible implications of the study could show the objective physicochemical properties associated with wine quality. Moreover, a goal of this study is to identify dominant physicochemical variables associated with the taste of wine. The results could provide valuable insight into wine production and consumer preference. 

The layout of this paper will be presented in several sections. The Data Section will discuss the source of the data and key features along with possible data limitations. The Model section will present the selected Linear Regression Model along with an explanation of the variables and properties of the model. Next, the Results section will present the results of the study with appropriate visualizations such as tables and graphs. Finally, the discussion section will be a commentary and analysis of the results along with weaknesses and potential next steps. 

# Data

The data used in this report was obtained through the UCI Machine Learning Repository [@citeUCI] and provided by [@citeVinho]. The statistical analysis in this report will be done using `R` [@citeR]. The R Packages, `tidyverse` [@citetidy] and `dplyr` [@citedplyr] will be used for data manipulation and cleaning. The graphs and tables for this report will created and formatted with `ggplot2` [@citeggplot] and `kableExtra` [@citekable]. The packages `bookdown` [@citebookdown] and `knitr` [@citeknitr] will be used to format this report.

## Data Limitations

# Model

# Results

# Discussion

## First discussion point

## Second discussion point

## Third discussion point

## Weaknesses and next steps

# Conclusion

\newpage

\appendix

# Appendix {-}


# Additional details


\newpage


# References


